version: '3.6'

services:

  postgres:
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    ports:
      - '${POSTGRES_PORT}:5432'
    volumes:
      - ./postgresql/dumps:/code/dumps
      - ./postgresql/data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    ports:
      - '6379:6379'
  
  # rabbitmq:
  #   image: rabbitmq:3-management-alpine
  #   container_name: 'rabbitmq'
  #   ports:
  #       - 5672:5672
  #       - 15672:15672
  #   volumes:
  #       - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
  #       - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq

  web:
    build: . 
    command: sh -c "/code/conf/run.sh"
    restart: always
    env_file:
    - .env
    ports:
      - '8000:8000'
    depends_on:
      - postgres
      - redis
      # - rabbitmq
    links:
      - "redis:redis"
    volumes:
      - ./public:/code/public
  

  celery:
    build: .
    env_file:
    - .env
    command: celery -A app worker --loglevel=info -B
    restart: always
    depends_on:
    - postgres
    - redis
    # - rabbitmq
    - web
    links:
      - "web:web"

    volumes:
    - ./public:/code/public